### PR TITLE
Add `dataprofiler` to NLP Tools Section

### PR DESCRIPTION
**Pull request by taylorfturner**
Adding `dataprofiler` to NLP tools: 
- repo: https://github.com/capitalone/DataProfiler
- Current docs: https://capitalone.github.io/DataProfiler/docs/0.8.0/html/index.html

Thanks!

### CODE REVIEW

**Comment by taylorfturner** [comment]
Bump. @lsbardel anyone in particular I should contact (tagging you since you are the last commit to `master`)? Thx.

**Comment by taylorfturner** [comment]
bump

**Comment by taylorfturner** [comment]
@lsbardel anything I can do to get this merged?

**Comment by taylorfturner** [comment]
Anything I can help with here @lsbardel? Thanks!

**Review by lsbardel — APPROVED** [review]

**Comment by lsbardel** [comment]
thanks

**Comment by taylorfturner** [comment]
> thanks

Thank you!

**Pull request merged**
